### ISSUE TITLE
Output is slightly borked on Mac.

### ISSUE THREAD

**Issue by leggettc18** [leggettc18/SequenceOTRizer#3]
It doesn't seem to cause any functionality issues, but some of the log output seems to be going to a new line and overwriting the contents of that line and it seems to be happening at the end of the otr database name right before the `_bgm` part. Not sure what's happening, but maybe inadvertently triggering some kind of escape sequence on mac os terminals?

**Comment by garrettjoecox** [comment]
Example output
```
musicArchive->AddFile(custom/music/NieR: Automata - Amusement Park_bgm)
musicArchive->AddFile(custom/music/Shovel Knight - Strike the Earth!_bgm)
_bgm)Archive->AddFile(custom/music/La Mulana - Mr Explorer
_bgm)Archive->AddFile(custom/music/La Mulana - Moon Light Dance
_bgm)Archive->AddFile(custom/music/La Mulana - Fearless Challenger
_bgm)Archive->AddFile(custom/music/La Mulana - Curse of Ocean
musicArchive->AddFile(custom/music/Bilby - Ty 2_fanfare)
musicArchive->AddFile(custom/music/Cog Get - Ty 2_fanfare)
```

**Comment by leggettc18** [comment]
So this is actually bigger than just output, somehow the file name ends up getting a carriage return character `\r` put into the metaName variable right before where the `_bgm` would go. It would seem that this is happening because getLine stops parsing on a newline character, not a carriage return character.
